name: docker

on:
  push: 
    branches: [main]
  workflow_dispatch:      

jobs:
  build-test-push: # job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2  
        
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1  
      - run : docker build ./src -t ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
          
      - name: Scan the Image container
        uses: Azure/container-scan@v0
        with:
         image-name: ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
#          login-server: ${{ secrets.DOCKER_USERNAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - run : docker push ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
