name: docker-kubernetes

on:
  push: 
    branches: [main]
  workflow_dispatch:      

jobs:
  docker: # job name
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v2
        
      - name: login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
#      - name: Kubernetes Set Context
#        uses: Azure/k8s-set-context@v2
#        with:
#          method: kubeconfig
#          kubeconfig: ${{ secrets.KUBE_CONFIG }}
     
      - name: build and push the docker image            
        run : |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aigatekeeper ./src 
          docker push ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
          minikube start
          kubectl apply -f k8s.yaml
 #         sed -i'' -e 's/ACR_URL/${{ secrets.ACR_URL }}/g' -e 's/AKS_URL/${{ secrets.AKS_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
 #         kubectl apply -f k8s.yaml
