name: docker build & push

on:
  push: 
    branches: [main]
  workflow_dispatch:      

jobs:
  docker: # job name
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: build and push to Docker Hub            
        run : |
          docker build ./src -t ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
          docker push ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
