name: docker build,test,push

on:
  push: 
    branches: [main]
  workflow_dispatch:      

jobs:
  docker: # job name
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v2
        
      - name: build the image container            
        run : docker build ./src -t ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
          
      - name: scan the image container
        uses: Azure/container-scan@v0
        with:
         image-name: ${{ secrets.DOCKER_USERNAME }}/aigatekeeper   
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: login to Docker Hub
        uses: docker/login-action@v1 
        with:
          login-server: ${{ secrets.DOCKER_USERNAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
   
      - name: push to Docker Hub   
        run : docker push ${{ secrets.DOCKER_USERNAME }}/aigatekeeper
