name: docker

on:
  push:
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Publish to Docker Hub  
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nimababak/AlGatekeeper
        tags: latest, ${{ github.run_number }}
